-- Template: use executable model UDFs + SQL utility UDFs.
-- Fill feature expressions from your feature view/materialized table.

SELECT
    driver_code,
    f1_team_encoder(driver_code) AS team,
    f1_win_probability_exec(
        grid_position,
        grid_position_group,
        avg_finish_last5,
        points_last5,
        dnf_rate_last5,
        team_enc,
        best_quali_lap,
        track_type_enc,
        laps_remaining,
        speed_rank_pct,
        delta_vs_field,
        tire_age,
        tire_age_pct,
        compound_enc,
        current_position,
        position_pct,
        is_leading,
        sc_active,
        position_jump_2,
        position_jump_3,
        sc_beneficiary,
        gap_to_leader_s,
        gap_laps_remaining,
        lap_progress,
        is_late_race,
        gap_urgency,
        leading_and_late,
        position_gain_pct,
        tire_freshness
    ) AS win_probability,
    f1_pit_probability_exec(
        compound_enc,
        tire_age,
        tire_age_pct,
        stint_len_med,
        stint_laps_left,
        stint_progress,
        current_lap,
        track_type_enc,
        avg_throttle,
        rainfall,
        delta_vs_field,
        speed_rank_pct,
        grid_position,
        avg_finish_last5,
        points_last5,
        dnf_rate_last5,
        team_enc,
        best_quali_lap,
        lap_progress,
        gap_urgency,
        tire_freshness,
        position_gain_pct,
        Stint,
        teammate_pitted,
        must_change_compound,
        gap_to_below_proxy,
        rel_speed_delta,
        pace_drop_5
    ) AS pit_probability,
    f1_pace_prediction_exec(
        avg_speed,
        compound_enc,
        tire_age,
        tire_age_pct,
        track_type_enc,
        rel_speed_delta,
        pace_drop_3,
        avg_throttle,
        avg_brake,
        hard_brake_rate,
        avg_drs,
        avg_rpm,
        track_temp,
        air_temp,
        rainfall,
        laps_remaining,
        LapNumber,
        race_pct,
        speed_rank_pct,
        delta_vs_field,
        gap_to_below_proxy,
        teammate_pitted
    ) AS predicted_laptime
FROM f1_feature_view
WHERE event = '2026_Japanese_Grand_Prix'
  AND year = 2026
  AND session = 'R'
  AND lap_no = 52;
